### ISSUE TITLE
Make a folder and file

### ISSUE THREAD

**Issue by woliul** [hmwoliul/data365#5]
# Warning :warning:
- সব কিছুর আগে খেয়াল রাখবা যে তুমি কোন `Branch` এ কাজ করছো।
- হয় নতুন `Branch` তৈরি কর অথবা HTML `Branch` Select কর। তার পর কাজ কর।

![screenshot-cloud githubusercontent com 2016-09-14 09-56-38](https://cloud.githubusercontent.com/assets/6556302/18499521/9867943e-7a61-11e6-8aba-3c58fc9556f5.png)
# Folder :file_folder:
- Make a **folder** with your own **code name**
- Like তোমার নামের প্রথম তিনটি অক্ষর বা তোমার ইচ্ছা মত একটা নামে Folder  বানাও। যাতে শুধু মাত্র তোমার কাজ করা ফাইল গুলো upload করা হবে।
# File :new:
- প্রত্যেকটি ফাইলের আগে দূটো লেটার ব্যবহার করবা। যেমন, ar_index.html এটা রিফাতের file এর জন্য আর ah_index.html এটা আহসান (ডেভিলের) file এর জন্য।
# Tutorial
- নিচের ছবি গুলো খেয়াল কর।
  ![1](https://cloud.githubusercontent.com/assets/6556302/18499327/c6dace78-7a5f-11e6-8b5d-f30186f7bde3.png)
  ![2](https://cloud.githubusercontent.com/assets/6556302/18499330/cb457666-7a5f-11e6-9e4c-fd518210f221.png)
# Resource

I invite you all to create and accept the invitation.
- https://data365.slack.com
- trello
- asana

**Comment by ghost** [comment]
vai color code koi 
https://github.com/hmwoliul/data365/milestone/1

Check kor

**Comment by woliul** [comment]
Folder koi? ah/dev007/ah_index.html emne type kor file namer jaygay

**Comment by ghost** [comment]
folder banaite partesina

**Comment by ghost** [comment]
banaile ki ase oita tou dekhtesen e .. bujhtesina kimne folder banay

**Comment by woliul** [comment]
ah/dev007.html
